CREATE TABLE  "PUBLISHED_OD" 
   (	"INDICATORFICHE_ID" NUMBER NOT NULL ENABLE, 
	"FICHE_UPDATE" TIMESTAMP (6), 
	"CIJFERS_UPDATE" TIMESTAMP (6), 
	"COMMENT_UPDATE" TIMESTAMP (6), 
	 CONSTRAINT "PUBLISHED_OD_PK" PRIMARY KEY ("INDICATORFICHE_ID")
  USING INDEX  ENABLE
   )
/
