perl 10_organisatie.pl
perl 20_personen.pl
perl 30_references.pl
perl 40_trefwoorden.pl
perl 50_gepubliceerd.pl
perl 60_frequenties.pl
perl 70_Frequenties.pl
perl 80_load_dimensies.pl
perl 100_indicatorfiche.pl
perl 190_load_txtable.pl
perl 192_load_indicatormap_table.pl
perl 194_indicatormap2txtable.pl
perl 205_indicator2fiche.pl
perl 210_get_dim_elementen.pl
